image: ubuntu:16.04

before_script:
    - apt-get update
    - apt-get install -y python3 python3-pip
    - pip3 install apache-libcloud

UnitTest:
    tags:
        - docker
    script:
        - ./run-tests.sh
